language: php

php: [5.5, 5.6, hhvm]

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
    - vendor

before_script:
  - echo 'extension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --prefer-dist --dev

script:
    - ./bin/phpspec run -fpretty
    - ./bin/funk funk
